name: Publish package to GitHub Packages

on:
  release:
    types: [published]
  main:
    types: [push]  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci

      # - name: Build and publish toolkit-cli
      #   run: |
      #       cd packages/toolkit-cli
      #       npm publish --access public
      #   env:
      #       NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}  

      - name: Build and publish toolkit-utils
        run: |
            cd packages/toolkit-utils
            npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}  
