name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # registry-url: 'https://npm.pkg.github.com'
      # - run: pnpm install

      # - name: Build and publish toolkit-cli
      #   run: |
      #       cd packages/toolkit-cli
      #       CURRENT_VERSION=$(node -p "require('./package.json').version")
      #       echo "current version: $CURRENT_VERSION"
      #       PUBLISHED_VERSION=$(npm view . version) || true
      #       echo "published version: $PUBLISHED_VERSION"
      #       if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
      #         npm publish --access public
      #       fi
      #   env:
      #       NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}  

      # - name: Build and publish toolkit-utils
      #   run: |
      #       cd packages/toolkit-utils
      #       CURRENT_VERSION=$(node -p "require('./package.json').version")
      #       echo "current version: $CURRENT_VERSION"
      #       PUBLISHED_VERSION=$(npm view . version) || true
      #       echo "published version: $PUBLISHED_VERSION"
      #       if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
      #         npm publish --access public
      #       fi
      #   env:
      #       NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}  

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: Install Dependencies
        run: pnpm install

      # - name: Build Packages
      #   run: pnpm run build

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @bossjobmatt:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to Github Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}

      # - name: Publish
      #   if: steps.changesets.outputs.hasChangesets == 'false'
      #   # You can do something when a publish should happen.
      #   run: pnpm release
