name: Tag on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_check.outputs.version }}
      tag_created: ${{ steps.create_tag.outputs.tag_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if version changed
        id: version_check
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $VERSION"

          if git tag --list "v$VERSION" | grep -q "^v$VERSION$"; then
            echo "⚠️ Tag v$VERSION already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Tag v$VERSION does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Git tag
        id: create_tag
        if: steps.version_check.outputs.exists == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ steps.version_check.outputs.version }} -m "Release v${{ steps.version_check.outputs.version }}"
          git push origin v${{ steps.version_check.outputs.version }}
          echo "✅ Successfully created and pushed tag v${{ steps.version_check.outputs.version }}"
          echo "tag_created=true" >> $GITHUB_OUTPUT
      
      - name: Skip tag creation
        id: skip_tag
        if: steps.version_check.outputs.exists == 'true'
        run: |
          echo "Tag already exists, skipping tag creation"
          echo "tag_created=false" >> $GITHUB_OUTPUT

  changelog:
    name: Create Changelog
    runs-on: ubuntu-latest
    needs: tag
    if: needs.tag.outputs.tag_created == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create Changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}